### ISSUE TITLE
Circular / bordered + size not works

### ISSUE THREAD

**Issue by tunnckoCore** [Semantic-Org/UI-Icon#4]
This not works if you are using this module as single.

```html
<link rel="stylesheet" href="https://cdn.rawgit.com/Semantic-Org/UI-Icon/master/icon.min.css">
<i class="circular users huge icon"></i>
<i class="bordered users huge icon"></i>
```

http://jsbin.com/vuboxa/1/edit?html,output

**Comment by tunnckoCore** [comment]
Hm. It seems that SUI uses Normalize v3.0.1, but that's not fully a truth. Replacing `UI-Reset` with the normalize v3.0.1 from the git repo, not fixes the problem.

**Comment by tunnckoCore** [comment]
It seems that if `i.bordered.icon` and `i.circular.icon` line-height is set to `line-height:2!important;` it just works as expected and not need of the `UI-Reset` which in meantime i cant understand why not just normalize.css without custom edit it. 

The only thing that it adds to the normalize v3.0.1 is

```css
/* Border-Box */
*,
*:before,
*:after {
  box-sizing: inherit;
}
html {
  box-sizing: border-box;
}

/* iPad Input Shadows */
input[type="text"],
input[type="email"],
input[type="search"],
input[type="password"] {
  -webkit-appearance: none;
  -moz-appearance: none;
  
/* mobile firefox too! */
}
```
and clearing few browser prefixes which are cleared in Normalize `v3.0.3`

So yea :)
